#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 10:34:09 2019

@author: davinpc
"""
#8
def find_longest_words(lwords):
    for i in lwords:
        sortedwords = sorted(lwords, key=len)
    a = sortedwords[-1]
    b = len(a)
    print(b)

find_longest_words(["string","hello","computer"])