#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 10:20:47 2019

@author: davinpc
"""
#6
def histogram(lst):
    for num in lst:
        print(num*"*")
        
histogram([4, 9, 7])