#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 27 12:01:41 2019

@author: davinpc
"""

def char_freq(str):
  freq = {}
  for c in str:
    if c in freq:
      freq[c] += 1
    else:
      freq[c] = 1
  return freq
      

#test
print(char_freq("abbabcbdbabdbdbabababcbcbab"))
print(char_freq("hello"))