#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 10:02:43 2019

@author: davinpc
"""
#4
a = [0,1,2,3,4,5]

def is_member(val):
    for i in a:  
        if (val == i) : 
            return True
    return False
  
print(is_member(2))
print(is_member(7))