#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 27 11:53:24 2019

@author: davinpc
"""

alpha = ['q','w','e','r','t','y','u','i','o','p','a','s','d','f','g','h','j','k','l','z','x','c','v','b','n','m', ' ']
sentence = 'The quick brown fox jumps over the lazy dog'
sentence = 'abcdefghijklmnopqrstuvwxyz '
def is_pangram(sentence):
    sentence1 = sentence.lower()
    sentence2 = sentence1.replace(' ','')
    for letter in sentence:
        if letter in alpha:
            return True
        else:
            return False


print(is_pangram(sentence))



