#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 26 11:17:08 2019

@author: davinpc
"""
#1

values = input("Input some comma seprated numbers : ")
list = values.split(",")
tuple = (*list, )
print('List : ',list)
print('Tuple : ',tuple)


