#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 13:21:10 2019

@author: davinpc
"""

def distance_from_zero(x):
    if  x == int or x == float:
        print(x)
    else:
        print("Nope")

distance_from_zero(-5.6)
distance_from_zero("what?")
