#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 12:13:13 2019

@author: davinpc
"""

def generate_n_chars(number,string):
   print(number*string)
        
generate_n_chars(5,"x")

