#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 13:10:56 2019

@author: davinpc
"""

def gross_pay():
    x = float(input("Enter hours: "))
    y = float(input("Rate: "))
    if x > 40:
        print("Pay: ", x*y*1.5)
    if x <= 40:
        print("Pay: ", x*y)
        
gross_pay()
    