#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 13:46:06 2019

@author: davinpc
"""

def piglatin():
    x = str(input("Enter a word in English: "))
    y = x.lower()
    z = y.replace(y[0],"")
    a = z + y[0] + "ay"
    print(a)
    
piglatin()