#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 11:53:29 2019

@author: davinpc
"""

#4
def vowel(str):
    if str == "a" or str == "i" or str == "e" or str == "u" or str == "o":
        print("True")
    else:
        print("False")
        

vowel("a")
vowel("b")