#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 11:00:39 2019

@author: davinpc
"""
#1
def max(x,y):
    if x > y :
        print(x)
        return x
    if y > x:
        print(y)
        return y

max(4,2)






    
    