#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 11:55:51 2019

@author: davinpc
"""

#7
def phrase_palindrome(str):
    a = str.replace(" ", "")
    b = a.lower()
    c = b.replace("?","")
    if c == c[::-1]:
        print("True")
    else:
        print("False")

phrase_palindrome("Rise to vote sir")
phrase_palindrome("Was it a rat I saw?")



