#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 13:00:39 2019

@author: davinpc
"""

def score(point):
    if point >= 0.9 and point <= 1.0:
        print("A")
    elif point >= 0.8 and point <= 1.0:
        print("B")
    elif point >= 0.7 and point <= 1.0:
        print("C")
    elif point >= 0.6 and point <= 1.0:
        print("D")
    elif point < 0.6 and point >= 0.0:
        print ("F")
    else:
        print("Error")
        
score(0.67)