#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 25 11:53:33 2019

@author: davinpc
"""

#6
def is_palindrome(str):
    if str == str[::-1]:
        print("True")
    else:
        print("False")
        
is_palindrome("hello")
is_palindrome("radar")